sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.6
  - 2.7.2
before_install:
  - sqlite3 -version
  - gem install bundler
script:
  - bundle exec rspec
  - bundle exec rubocop -R
gemfile:
  - gemfiles/sidekiq_5.gemfile
  - gemfiles/sidekiq_6.gemfile
  - gemfiles/rails_6.gemfile
matrix:
  fast_finish: true
jobs:
  exclude:
    - rvm: 2.3.8
      gemfile: gemfiles/rails_6.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/rails_6.gemfile
