sudo: false
language: ruby
cache: bundler
rvm:
  - 2.7.5
  - 3.0.3
before_install:
  - sqlite3 -version
  - gem install bundler
script:
  - bundle exec rspec
  - bundle exec rubocop -R
gemfile:
  - gemfiles/sidekiq_5.gemfile
  - gemfiles/sidekiq_6.gemfile
  - gemfiles/rails_6.gemfile
matrix:
  fast_finish: true
